<?php
/**
 * Theme functions and definitions.
 * This child theme was generated by Conikal.
 *
 * @link https://developer.wordpress.org/themes/basics/theme-functions/
 */

/*
 * If your child theme has more than one .css file (eg. ie.css, style.css, main.css) then
 * you will have to make sure to maintain all of the parent theme dependencies.
 *
 * Make sure you're using the correct handle for loading the parent theme's styles.
 * Failure to use the proper tag will result in a CSS file needlessly being loaded twice.
 * This will usually not affect the site appearance, but it's inefficient and extends your page's loading time.
 *
 * @link https://codex.wordpress.org/Child_Themes
 */

add_action( 'wp_enqueue_scripts', 'conikal_campoal_child_styles', 10 );
function conikal_campoal_child_styles() {
wp_enqueue_style('campoal-style', get_template_directory_uri() . '/style.css', array(), wp_get_theme()->parent()->get('Version'));
    wp_enqueue_style('campoal-child', get_stylesheet_directory_uri() . '/style.css', array('campoal-style'), wp_get_theme()->get('Version'));
}

/** Place any new code below this line */

function campoal_child_enqueue_styles() {
    wp_enqueue_style('campoal-child-style',
        get_stylesheet_directory_uri() . '/style.css',
        array('campoal-style'),
        wp_get_theme()->get('Version')
    );
}
add_action('wp_enqueue_scripts', 'campoal_child_enqueue_styles');

// Ensure proper dropdown initialization
function campoal_child_menu_classes($classes, $item) {
    if (in_array('menu-item-has-children', $classes)) {
        $classes[] = 'ui dropdown';
    }
    return $classes;
}
add_filter('nav_menu_css_class', 'campoal_child_menu_classes', 10, 2);



/** Load in the loading screen */

function enqueue_loading_screen() {
    wp_enqueue_style('loading-screen', get_stylesheet_directory_uri() . '/loading-screen/loading-screen.css');
    wp_enqueue_script('loading-screen', get_stylesheet_directory_uri() . '/loading-screen/loading-screen.js', array('jquery'), '1.0', true);
}
add_action('wp_enqueue_scripts', 'enqueue_loading_screen');



/** Load in Mega Menu */

function register_mega_menu() {
    register_nav_menu('mega-menu', __('Mega Menu'));
}
add_action('init', 'register_mega_menu');

function enqueue_mega_menu() {
    wp_enqueue_style('mega-menu', get_stylesheet_directory_uri() . '/mega-menu/mega-menu.css');
    wp_enqueue_script('mega-menu', get_stylesheet_directory_uri() . '/mega-menu/mega-menu.js', array(), '1.0', true);
}
add_action('wp_enqueue_scripts', 'enqueue_mega_menu');



/** Load in Mega Menu Quadrants */

class Quadrant_Menu_Walker extends Walker_Nav_Menu {
    public function start_lvl(&$output, $depth = 0, $args = array()) {
        $output .= "<ul class='sub-menu'>";
    }
    
    public function end_lvl(&$output, $depth = 0, $args = array()) {
        $output .= "</ul>";
    }
}



/** Load in Mega Menu */

function enqueue_mega_menu_scripts() {
    wp_enqueue_style('mega-menu-styles', get_template_directory_uri() . '/mega-menu/mega-menu.css');
    wp_enqueue_script('mega-menu-script', get_template_directory_uri() . '/mega-menu/mega-menu.js', array('jquery'), '1.0', true);
}
add_action('wp_enqueue_scripts', 'enqueue_mega_menu_scripts');



/** Load in Splash Screen */

function enqueue_splash_screen() {
    wp_enqueue_style('splash-screen', get_template_directory_uri() . '/loading-screen/splash-screen.css');
    wp_enqueue_script('splash-screen', get_template_directory_uri() . '/loading-screen/splash-screen.js', array(), '1.0', true);
}
add_action('wp_enqueue_scripts', 'enqueue_splash_screen');
