<?php
/**
 * Theme functions and definitions.
 * This child theme was generated by Conikal.
 *
 * @link https://developer.wordpress.org/themes/basics/theme-functions/
 */

add_action( 'wp_enqueue_scripts', 'conikal_campoal_child_styles', 10 );
function conikal_campoal_child_styles() {
    wp_enqueue_style('campoal-style', get_template_directory_uri() . '/style.css', array(), wp_get_theme()->parent()->get('Version'));
    wp_enqueue_style('campoal-child', get_stylesheet_directory_uri() . '/style.css', array('campoal-style'), wp_get_theme()->get('Version'));
}

/** Place any new code below this line */

function campoal_child_enqueue_styles() {
    wp_enqueue_style('campoal-child-style',
        get_stylesheet_directory_uri() . '/style.css',
        array('campoal-style'),
        wp_get_theme()->get('Version')
    );
}
add_action('wp_enqueue_scripts', 'campoal_child_enqueue_styles');

// Force home-header.php everywhere
function force_home_header() {
    remove_all_actions('get_header');
    add_action('get_header', function() {
        get_template_part('templates/header/home-header');
    }, 1);
}
add_action('after_setup_theme', 'force_home_header', 11);

// Ensure proper dropdown initialization
function campoal_child_menu_classes($classes, $item) {
    if (in_array('menu-item-has-children', $classes)) {
        $classes[] = 'ui dropdown';
    }
    return $classes;
}
add_filter('nav_menu_css_class', 'campoal_child_menu_classes', 10, 2);

/** Load in the loading screen */
function enqueue_loading_screen() {
    // Remove the old loading screen enqueue
    wp_dequeue_script('loading-screen');
    
    // Add the loading screen with priority 1 to load first
    wp_enqueue_style('loading-screen', get_stylesheet_directory_uri() . '/loading-screen/loading-screen.css');
    wp_enqueue_script('loading-screen', get_stylesheet_directory_uri() . '/loading-screen/loading-screen.js', array('jquery'), '1.0', false);
    
    // Add loading screen initialization
    wp_add_inline_script('loading-screen', 'document.documentElement.style.visibility = "hidden";', 'before');
}
add_action('wp_enqueue_scripts', 'enqueue_loading_screen', 1);

/** Load in Mega Menu */
function register_mega_menu() {
    register_nav_menu('mega-menu', __('Mega Menu'));
}
add_action('init', 'register_mega_menu');

function enqueue_mega_menu() {
    wp_enqueue_style('mega-menu', get_stylesheet_directory_uri() . '/mega-menu/mega-menu.css');
    wp_enqueue_script('mega-menu', get_stylesheet_directory_uri() . '/mega-menu/mega-menu.js', array(), '1.0', true);
}
add_action('wp_enqueue_scripts', 'enqueue_mega_menu');

/** Load in Mega Menu Quadrants */
class Quadrant_Menu_Walker extends Walker_Nav_Menu {
    public function start_lvl(&$output, $depth = 0, $args = array()) {
        $output .= "<ul class='sub-menu'>";
    }
    
    public function end_lvl(&$output, $depth = 0, $args = array()) {
        $output .= "</ul>";
    }
}



function enqueue_user_menu_assets() {
    wp_enqueue_style('user-menu-style', get_stylesheet_directory_uri() . '/user-menu/user-menu.css', array(), '1.0.0');
    wp_enqueue_script('user-menu-script', get_stylesheet_directory_uri() . '/user-menu/user-menu.js', array('jquery'), '1.0.0', true);
}
add_action('wp_enqueue_scripts', 'enqueue_user_menu_assets');
